### ISSUE TITLE
Definir estrutura e nomenclatura

### ISSUE THREAD

**Issue by volooptaz** [blouco/openblouco#1]
Trazendo para cá o que disse Elaine no etherpad:

> O projeto tem como estrutura base o Carnaval de Rua, utilizando sistemas gratuitos e de código aberto,tem como objetivo a aglomeração virtual em prol da colaboração criativa. 
> 
> 0.0 - Rua - Home
> 
> É nessa página em que todo mundo se encontra. 
> 
> Componentes:
> 
> 0.0.1 - Como funciona: Recebem boas vindas e as regras de participação
> 0.0.2 - Destaque: Descobrem quais Blocos estão rolando no momento
> 0.0.3 - Programação: Grade programática de Blocos futuros
> 0.0.4 - Concentração: Chat para encontrar pessoas e esperar o início dos blocos
> 0.0.5 - Festinha: Podem co-criar uma música midi utilizando o jamhub.io 
> 
> 1.0 - BLOCOS
> Cada bloco tem seu estandarte, nome aleatório e página com link único, que será utilizado para convocação dos foliões nas redes sociais.    -> Gerado pelo HashFolia https://hash.bloucos.art/EnsaioDoBlouco
> 
> Aberto a todes, a página do BLOCO conta com um embed de vídeo para transmissão gerenciado por OBS, com a composição dos seus acontecimentos:    -> exemplo: https://blouco.neocities.org/BodeAludidoExcretor.html
>     
>  Live do Artista (Twitch ou Youtube) ou Banda Colab (Jamulus)
> Trio Elétrico, que é a sala Jisti que exibe imagens das 20 pessoas que estão acompanhando o Bloco de perto e solicitaram a participação no Cordão
> 
> Componentes:
> 
> 1.0.1 - Embed de Transmissão
> 1.0.2 - Cordão - Chat de mediação onde os Foliões podem 
> 
> retirar um dos 20 tickets para participar do Trio Elétrico (Sala do Jitsi com transmissão na Página do Bloco)
> no caso de um Bloco Colab (Bonde), solicitar a entrada na Jam via Jamulus
> 
> Os blocos podem ser de três tipos:
>     
> 1) Palco: um Artista (DJ, Músico, Performer) transmite sua live, que pode ser um embed do Twitch ou Youtube, a ser gerado pelo próprio artista
>    
> 2) Colaborativos: Utilizando Jamulus, um grupo de pessoas transmite uma apresentação ao vivo, que pode adicionar pessoas que solicitarem participação
> 
> 3) Concursos: Propõe uma dinâmica que envolve um APRESENTADOR e múltiplos canais conectados ao OBS, como por exemplo, um concurso de marchinhas: Todos os participantes devem enviar sua incrição e prepararem para a apresentação de sua performance via Jamulus. Durante a performance, será exibida a performance ao vivo e a receptividade do Trio (Jitsi). Ao final, todos que estão na página do bloco podem votar na sua marchinha preferida via CHAT (?) 
> 
> Neste modelo é possível também realizar Concurso de Fantasias, Melhor Samba no Pé ou qualquer outro critério pré-definido. 
> 
> 
> 2.0 - Trio Elétrico (Sala do Jitsi)
> Vinculado ao Bloco, é a Sala de Chat com limite de 20 lugares, cujas imagens serão transmitidas no vídeo de transmissão na página do Bloco.
> 
> ++++
> 
> Ó: a estrutura acima pensa no fechamento do circuito completo, pensando na multiplicação dos tipos de bloco de acordo com as ferramentas colabs disponíveis e escalabilidade do CARNAVAL como um todo. 
> 
> Para o dia 14, por exemplo, podemos ter só a página do BLOCO com vídeo, chat e uma ÚNICA GRADE de programação no Embed, gerenciado por OBS
> 
> ++++
> 
> Quando todos estivermos de acordo com a estrutura e nomenclatura, vamos esmiuçar e trazer os textos abaixo pro modelo aí de cima. É com isso que vamos trabalhar identidade, tom de voz e manuais de uso para os diversos papéis.

**Comment by zeivic** [comment]
"Para o dia 14, por exemplo, podemos ter só a página do BLOCO com vídeo, chat e uma ÚNICA GRADE de programação no Embed, gerenciado por OBS".

Concordo com esse modelo. Aqui poderiam entrar as vinhetas gravadas para colocar na transição de uma atividade para outra, em uma grade única. 
Podemos testar esse modelo antes e depois a gente tenta replicar de forma simultânea.

**Comment by volooptaz** [comment]
> Concordo com esse modelo. Aqui poderiam entrar as vinhetas gravadas para colocar na transição de uma atividade para outra, em uma grade única.

Sim!

> Podemos testar esse modelo antes e depois a gente tenta replicar de forma simultânea.

Podemos. Vou responder alguns detalhes em linha puxando ali do primeiro post

**Comment by volooptaz** [comment]
> 0.0 - Rua - Home
> 
> É nessa página em que todo mundo se encontra. 
> 
> Componentes:
> 
> 0.0.1 - Como funciona: Recebem boas vindas e as regras de participação
> 0.0.2 - Destaque: Descobrem quais Blocos estão rolando no momento
> 0.0.3 - Programação: Grade programática de Blocos futuros
> 0.0.4 - Concentração: Chat para encontrar pessoas e esperar o início dos blocos
> 0.0.5 - Festinha: Podem co-criar uma música midi utilizando o jamhub.io 


Gostei muito desse modelo. Mas o chat não precisa servir só como concentração, e sim como ambiente mesmo onde as pessoas podem ficar no chat.

Como vamos ter múltiplas salas de vídeo (ver a #12) , ter a Rua ali à disposição com o chat serve de meio central e de emergência para a comunicação entre todos os "Bondes" (como estou chamando cada sala de vídeo).



> 1.0 - BLOCOS
> Cada bloco tem seu estandarte, nome aleatório e página com link único, que será utilizado para convocação dos foliões nas redes sociais.    -> Gerado pelo HashFolia https://hash.bloucos.art/EnsaioDoBlouco
> 
> Aberto a todes, a página do BLOCO conta com um embed de vídeo para transmissão gerenciado por OBS, com a composição dos seus acontecimentos:    -> exemplo: https://blouco.neocities.org/BodeAludidoExcretor.html

Aqui tem um detalhe, que no modelo que pensei um Blouco não tem um único Estandarte, e sim uma sucessão deles (colando da #10, mais detalhes lá dentro):

> Outro é a mudança de salas mesmo, que envolveria as pessoas mudarem para novas salas geradas de um novo Estandarte. Na descrição da ö ela coloca um Estandarte por bloco, mas na verdade a intenção inicial era que o Estandarte representasse um "turno" de movimento do Blouco, sendo recriado a partir do hash do anterior e portanto vinculado a ele, mas gerando imagens e salas completamente novas.


>  Live do Artista (Twitch ou Youtube) ou Banda Colab (Jamulus)
> Trio Elétrico, que é a sala Jisti que exibe imagens das 20 pessoas que estão acompanhando o Bloco de perto e solicitaram a participação no Cordão
> 
> Componentes:
> 
> 1.0.1 - Embed de Transmissão
> 1.0.2 - Cordão - Chat de mediação onde os Foliões podem 
> 
> retirar um dos 20 tickets para participar do Trio Elétrico (Sala do Jitsi com transmissão na Página do Bloco)
> no caso de um Bloco Colab (Bonde), solicitar a entrada na Jam via Jamulus

OK, esta é a parte que vai ficar de qualquer maneira a mais aberta e livre, mas ao mesmo tempo é a que precisamos fechar mais para o ensaio do domingo.

Vamos discutir esta questão da coordenação dos Trios e seus Bondes na #12, em coordenação com a documentação das Puxadoras (#16)


> 
> Os blocos podem ser de três tipos:
>     
> 1) Palco: um Artista (DJ, Músico, Performer) transmite sua live, que pode ser um embed do Twitch ou Youtube, a ser gerado pelo próprio artista
>    
> 2) Colaborativos: Utilizando Jamulus, um grupo de pessoas transmite uma apresentação ao vivo, que pode adicionar pessoas que solicitarem participação
> 
> 3) Concursos: Propõe uma dinâmica que envolve um APRESENTADOR e múltiplos canais conectados ao OBS, como por exemplo, um concurso de marchinhas: Todos os participantes devem enviar sua incrição e prepararem para a apresentação de sua performance via Jamulus. Durante a performance, será exibida a performance ao vivo e a receptividade do Trio (Jitsi). Ao final, todos que estão na página do bloco podem votar na sua marchinha preferida via CHAT (?) 
> 
> Neste modelo é possível também realizar Concurso de Fantasias, Melhor Samba no Pé ou qualquer outro critério pré-definido. 

Como estamos aqui já discutindo a nomenclatura, proponho considerarmos o Blouco o "todo", incluindo as pessoas que estão no chat e nas outras plataformas que podem estar ou não vinculadas a essas atividades,ser criadas espontaneamente pelos participantes, sem um fechamento estrito, com a única definição de o ambiente estar alinhado ao Estandarte e às Puxadoras.

Em termos mysticos seria como a "egrégora" ou "forma-pensamento" formada pelo conjunto de pessoas sintonizadas. Como na imagem "Forma pensamento da música" de Charles Gounoud

![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Music_of_Gounod_-_Annie_Besant_Thought_Form_-_Project_Gutenberg_eText_16269.jpg/180px-Music_of_Gounod_-_Annie_Besant_Thought_Form_-_Project_Gutenberg_eText_16269.jpg)

Mas enfim, heheh, criei uma outra issue para discutirmos isso:


> 2.0 - Trio Elétrico (Sala do Jitsi)
> Vinculado ao Bloco, é a Sala de Chat com limite de 20 lugares, cujas imagens serão transmitidas no vídeo de transmissão na página do Bloco.

Vamos levar esta discussão para o #15

**Comment by volooptaz** [comment]
Trazendo a #22 pra cá:

Proposta de um roteiro linear para a criação  de um Blouco a partir de uma sala de Jitsi:

---

Um grupo de pessoas está no Bonde Semente (sala Jitsi).

Uma delas se consagra Porta-estandarte ao fazer  uma consulta ao Blouco através do HashFolia, utilizando uma poesia, invocação ou outro texto que achar apropriado como semente. https://hash.bloucos.art/<SEMENTE>. 

Porta-estandarte gera um novo documento Estandarte, através da saída  revelada pelo Blouco através do HashFolia. 

Porta-estandarte acessa a PÁGINA DA PORTA-ESTANDARTE.  Componentes:

- Materiais: https://github.com/blouco/openblouco/issues/21
- Estandarte - Etherpad
- Bonde Semente - Jitsi

Porta Estandarte consagra uma ou mais Puxadoras dentre as outras pessoas presentes no Bonde, lhes concedendo acesso à PÁGINA DAS PUXADORAS.  Componentes:

- Materiais: https://github.com/blouco/openblouco/issues/16
- Estandarte - Etherpad
- Bonde Semente - Jitsi
- Papo - salas principal e do cordão

Puxadoras devem todas serem tornadas administradoras do Bonde Semente.

Puxadoras criam/reivindicam administração das salas do Papo (canais Principal e Cordão no servidor IRC), do Bonde (Jitsi), do Trio (OBS.ninja)

Puxadoras consagram uma ou mais Artistas, sendo uma delas a Mixer, lhes concedendo acesso à PÁGINA DAS ARTISTAS. Componentes:

- Materiais: https://github.com/blouco/openblouco/issues/15
- Estandarte - Etherpad
- Bonde Semente - Jitsi
- Papo - salas principal e do cordão
- Sala da Mixer - OBS.ninja (se ?mixer, sala de controle)

Artista-mixer entra na PÁGINA DAS ARTISTAS, assumindo controle do Trio (OBS.ninja), iniciando sua transmissão (Youtube)., e fornecendo o link da stream para a Puxadora.

Artista-mixer gerencia outros Artistas em suas apresentações, ou conduz seu próprio trabalho artístico de DJng, VJng, etc.

Artista-mixer (ou alguém sob sua delegação) compartilha a transmissão dentro do Bonde Semente (Jitsi_, utilizando a funcionalidade de compartilhamento de links do Youtube.

Puxadoras consagram uma ou mais Passistas, lhes concedendo acesso à PÁGINA DAS PASSISTAS. Componentes:

- Materiais: https://github.com/blouco/openblouco/issues/19
- Bonde Semente - Jitsi
- Papo - salas principal e do cordão

Puxadoras consagram uma ou mais Cordões, lhes concedendo acesso à PÁGINA DAS CORDÕES.  Componentes:

- Materiais: https://github.com/blouco/openblouco/issues/18
- Bonde Semente - Jitsi
- Papo - salas principal e do cordão
- Sala da Mixer - OBS.ninja

Cordões entram na PÁGINA DAS CORDÕES, entrando nas salas do Papo (Principal e Cordão).

Puxadora cria a Rua (página Web). Componentes:

- Como funciona / Materiais: https://github.com/blouco/openblouco/issues/17
- Transmissão do Trio - embed do Youtube
- Sala principal do Papo - Freenode Webchat
- Doações - Link para Pix da Garagem das Ambulantes

Cordões gerem a entrada e permanência de Incautas, e sua passagem para o Trio e os Bondes.

**Comment by volooptaz** [comment]
Consegui pensar uma dinamica simples e boa pra gerir o Trio (onde a Mixer coordena as artistas tocando no OBS.ninja e faz a transmissão pra uma stream) e os Bondes (1+ sala(s) de Jitsi) que devem receber essa transmissão pra dentro da sala, ao fazer o roteiro que propus em #22 .

Como o Jitsi torna bem simples compartilhar videos do youtube com todes, se restringirmos a stream de saída a ser do youtube fica muito fácil fazer a transmissão do Trio chegar tanto a Rua quanto nos Bondes

O template ajustado que vc subiu @zeivic , ficou bem legal! Dentro aí do roteiro eu proponho o que to pensando há 2 dias já, que é fazer um sisteminha simples em python complementar ao HashFolia que gere além da rua, páginas para cada Função

Seria algo como

`bloucos.art/artistas/?jitsi=FrasePalavras1&estandarte=FrasePalavras2&papo=FrasePalavras3&obsninja=FrasePalavras4`

A própria Rua não seria mais uma página com as salas hardcoded e sim um desses

`bloucos.art/rua/?transmissao=CodYoutube&papo=FrasePalavras3`

**Comment by volooptaz** [comment]
A princípio acho que fechamos a nomenclatura. A Elaine se afastou por uns dias então está mesmo em nossas mãos tocar isso por enquanto. Fechando a thread, qualquer coisa reabrimos!

**Comment by zeivic** [comment]
vamos testar essa dinâmica no ensaio? Eu não entendi se acontece na página do trio ou só dentro do chat.

**Comment by volooptaz** [comment]
Testamos a dinâmica no ensaio, creio que temos a nomenclatura fechada :-) entre https:;//open.bloucos.art e o https://hash.bloucos.art/hash/
