### ISSUE TITLE
Movimentação do Blouco: encadeamento de Estandartes

### ISSUE THREAD

**Issue by volooptaz** [blouco/openblouco#10]
- Caminhos do blouco - uma vez que o blouco tome forma, podemos (com a movimentação das Puxadoras) "marchar" com ele juntes para visitar páginas, grupos, hashtags etc e convidas as pessoas

**Comment by zeivic** [comment]
essa dinâmica de visitações, vamos usar o obs ninja refletindo os espaços?

**Comment by volooptaz** [comment]
Trouxe a #10 para cá também.  Trazendo os quotes:

> na ausência ou paralelamente com as performances dos artistas, a gente pode ir mostrando coisas assim na tela, que as pessoas possam abrir junto e interagir ao vivo (bem, nao as com celular)
> 
> tipo, abrir num video do youtube e td mundo brotar nos comentarios
> 
> e é um pouco por isso que eu to pensando esse lance do chat simples no IRC com moderação dos "cordões", meio cenário de guerra, porque eu queria que a gente conseguisse montar uma "estrutura" que pudesse ir se movendo por aí e colando o link pra Rua pela web e chamando as pessoas, sem o risco de cair um monte de gente zoada no meio do Jitsi e de quem tá tocando

---

> ##Processos e características de um bloco autônomo**
> 
> (escrevi isso quando tava no comecinho do Blouco, a partir das minhas experiências com o Boi Tolo, Tecnobloco, outros blocos autônomos / anárquicos do Rio:
> 
> 
> - Ele sempre anda, e vai mantendo sua forma - uma espécie deautoorganização / autopoiese
> - Está sempre em um diálogo com os arredores, se comunicando, interagindo, incorporando as pessoas e os ambientes pelas quais ele passa
> - Ele está sempre se reorganizando para que os músicos mantenham as formações 
> - As pessoas mais montadas, que vão de perna de pau, os músicos, etc, têm um poder intrínseco de orientar, impôr o ritmo, resolver conflitos e tomar decisões. Uma rede social muito coesa, embora de aparência caótica, se forma, e o bloco como um todo ganha uma individualidade e passa a parecer comandado para quem está de fora.
> - Por não ter lideranças nem hierarquias definidas, a forma de seguir o bloco é conectar-se com o ritmo da banda (principalmente os tambores) e seguir os estandartes -- os do próprio bloco, que são na prática o elemento central de cada bloco, e os que surgem ao longo dos carnavais e ganham sua própria reputação subjetiva de proporcionar bons caminhos.
> - Conforme a harmonia, a sincronização e a entrega entre as pessoas vai ocorrendo, a música começa a “pegar” e ele segue tocando várias marchinhas geradas espontaneamente pela “egrégora”: a todo momento pessoas puxam novas músicas, ou mesmo ouvem uma música errada e reverberam, e o bloco faz a transição se há concordância
> - Várias marchinhas tocadas  do repertório clássico do Carnaval (“Abre Alas”, “Índio Quer Apito”, “Alalaô”) funcionam na prática como códigos de comunicação, seja por sua letra ou por seu ritmo, sobre o que o bloco irá fazer (começar a andar com maior rapidez, parar para aumentar a sincronia e a coesão da banda, buscar água para os músicos)
> - Ele pode se chocar com outros blocos ou com grandes grupos, e gerar um momento de confusão.
> - Ele pode se dividir e gerar novos blocos com a “vibe” ou “egrégora” daqueles que saíram
>

**Comment by volooptaz** [comment]
> essa dinâmica de visitações, vamos usar o obs ninja refletindo os espaços?

Nesse caso @zeivic, eu acho que está mesmo confuso porque tem dois componentes essa "movimentação" e presença na Web, e eu meio que misturei eles lá em cima na mensagem original:

- Um é este que você está descrevendo, onde a stream exibe um site e as pessoas são convidadas a interagir com ele para *além* de onde elas já estão (IRC / Rua, jitsi / Bondes).

- Outro é a mudança de salas mesmo, que envolveria as pessoas mudarem para novas salas geradas de um novo Estandarte. Na descrição da ö ela coloca um Estandarte por bloco, mas na verdade a intenção inicial era que o Estandarte representasse um "turno" de movimento do Blouco, sendo recriado a partir do hash do anterior e portanto vinculado a ele, mas gerando imagens e salas completamente novas.

Este último é para simular alguns aspectos dos blocos autônomos que eu descrevo aí em cima. Aí o bloco "andar" seria as salas serem trocadas, e aí as Puxadoras ficariam responsáveis por avisar o resto da equipe, e as outras pessoas acompanham este movimento junto. 

É uma feature "avançada", rs, que não tenho certeza se seria fácil de coordenar, mas que geraria uma possibilidade interessante de manter engajadas as pessoas que estivessem com laços fortalecidos com o bloco, como faz o Boi Tolo que não pára de andar e com isso consegue atrair multidões sem "estagnar" ou lotar de pessoas nada a ver, sem precisar lidar também com expulsões e moderação -- as pessoas que se perderem simplesmente vão ficando pelas salas anteriores.

**Comment by volooptaz** [comment]
Fiz essa representação gráfica aqui pra tentar complementar o que tô tentando comunicar, ó

![sucessao](https://user-images.githubusercontent.com/73457921/107122310-d0e40980-6875-11eb-9ca2-05040f5be2d7.png)

**Comment by zeivic** [comment]
A imagem ficou boa, peguei a dinâmica, eu só não compreendi como tecnicamente isso vai acontecer. Eu ainda não entendi o que é gerado e o que será puxado por uma pessoa de fato. No ensaio eu vou entender.

**Comment by volooptaz** [comment]
Acho que deu pra entender a ideia geral né? Vou incorporar essa imagem na documentação do OpenBlouco mas no fim quem tem que saber disso mais é a Porta-estandarte, que serei euzinhe :-)
