### ISSUE TITLE
Materiais: Incautas

### ISSUE THREAD

**Issue by volooptaz** [blouco/openblouco#17]
Issues relevantes:

#2 

#3

**Comment by volooptaz** [comment]
Incorporando #2


---

> 🎶  bota a camisinha, bota meu amor 🎶
> 
> Links para guias rápidos de proteção e malandragem na web, e recomendações de extensões para acompanhar o blouco com segurança.

---

@zeivic :

> essa informação entra na página da documentação ou na Rua?

**Comment by volooptaz** [comment]
@zeivic estou pensando em colocar todas as documentações mesmo no site, e linkar esta em específico da Rua (linkada na página "Funções > Incautas"

Que acha? A ideia é que cada pessoa possa ser orientada, a partir do que quer fazer, através da página da Função respectiva.

**Comment by volooptaz** [comment]
Este guia de introdução ao IRC é muito bom e na falta de outro material podemos usá-lo, em tradução automática mesmo, como material de Incauta e também (principalmente) para Cordões:

[IRC Introduction and its main ingredients](https://medium.com/the-complete-guide-for-irc-network-i-e-freenode/irc-introduction-and-its-main-ingredients-982cd3639a67)

**Comment by zeivic** [comment]
> 
> 
> @zeivic estou pensando em colocar todas as documentações mesmo no site, e linkar esta em específico da Rua (linkada na página "Funções > Incautas"
> 
> Que acha? A ideia é que cada pessoa possa ser orientada, a partir do que quer fazer, através da página da Função respectiva.

Em uma seção no começo da página me parece organizado, ou dividir a coluna e colocar próximo do chat.

**Comment by volooptaz** [comment]
> > @zeivic estou pensando em colocar todas as documentações mesmo no site, e linkar esta em específico da Rua (linkada na página "Funções > Incautas"
> > Que acha? A ideia é que cada pessoa possa ser orientada, a partir do que quer fazer, através da página da Função respectiva.
> 
> Em uma seção no começo da página me parece organizado, ou dividir a coluna e colocar próximo do chat.

Boa. Vou fechar mais esta issue "Materiais:" e levar isso para uma nova
