### ISSUE TITLE
Materiais - Cordões

### ISSUE THREAD

**Issue by volooptaz** [blouco/openblouco#18]
Issues relevantes:

#3 
#5 
#4 
#12

**Comment by volooptaz** [comment]
Trazendo #4 e #5 para cá:


### moderação coletiva / código de conduta

> como intermediar conflitos e manter um ambiente seguro nos espaços do Blouco, da forma mais descentralizada possível?


### Uso de bots nas salas de chat

Sopel is a simple, easy-to-use, open-source IRC utility bot, written in Python. It’s designed to be easy to use, easy to run, and easy to extend.
https://sopel.chat/

CloudBot is a simple, fast, expandable open-source Python IRC Bot!
https://github.com/TotallyNotRobots/CloudBot

**Comment by volooptaz** [comment]
Sobre bots, algo que é simples e pode ser bem divertido é colocar bots no canal principal do Papo, soltando frases de tempos em tempos baseadas  em cadeias de Markov (como autocompletar do celular).

Aqui um exemplo feito por essa [ferramenta online](https://projects.haykranen.nl/markov/demo/) usando umas 10 letras de marchinha:

[![](https://user-images.githubusercontent.com/73457921/107124179-fe828000-6880-11eb-9cd6-f19451dd986c.png)
](url)

Programando diretamente é possível fazer o bot cuspir conteúdos mais elaborados, começando com uma determinada palavra por exemplo, ou alimentar ele usando o conteúdo já presente no chat. Também é possível fazer com que isso aconteça de tempos em tempos, ou acionado por um comando por mensagem.

Aqui um links interessante mais explicado sobre como criar bots de IRC:

https://hackernoon.com/make-a-retro-chatbot-for-irc-3eada517967

E projeto do qual esse artigo fala, menos sofisticado para projetos maiores mas mais fácil de aprender / adaptar para projetos mais simples e por iniciantes:

- botymcbotface: https://www.github.com/enfors/botymcbotface.git
- example_bot.py: https://gist.github.com/Enfors/293e904e40f407d492868977628a35cd

**Comment by volooptaz** [comment]
Este guia de introdução ao IRC é muito bom e na falta de outro material podemos usá-lo, em tradução automática mesmo, como material de Incauta e também (principalmente) para Cordões:

[IRC Introduction and its main ingredients](https://medium.com/the-complete-guide-for-irc-network-i-e-freenode/irc-introduction-and-its-main-ingredients-982cd3639a67)

**Comment by zeivic** [comment]
> 
> 
> Sobre bots, algo que é simples e pode ser bem divertido é colocar bots no canal principal do Papo, soltando frases de tempos em tempos baseadas em cadeias de Markov (como autocompletar do celular).
> 
> Aqui um exemplo feito por essa [ferramenta online](https://projects.haykranen.nl/markov/demo/) usando umas 10 letras de marchinha:
> 
> [![](https://user-images.githubusercontent.com/73457921/107124179-fe828000-6880-11eb-9cd6-f19451dd986c.png) ](url)
> 
> Programando diretamente é possível fazer o bot cuspir conteúdos mais elaborados, começando com uma determinada palavra por exemplo, ou alimentar ele usando o conteúdo já presente no chat. Também é possível fazer com que isso aconteça de tempos em tempos, ou acionado por um comando por mensagem.
> 
> Aqui um links interessante mais explicado sobre como criar bots de IRC:
> 
> https://hackernoon.com/make-a-retro-chatbot-for-irc-3eada517967
> 
> E projeto do qual esse artigo fala, menos sofisticado para projetos maiores mas mais fácil de aprender / adaptar para projetos mais simples e por iniciantes:
> 
>     * botymcbotface: https://www.github.com/enfors/botymcbotface.git
> 
>     * example_bot.py: https://gist.github.com/Enfors/293e904e40f407d492868977628a35cd

Genial! Eu gosto da dinâmica dele usar palavras do próprio chat, porém, eu tenho receio de que possa sair algo inconveniente também ou desrespeitoso. Para um divertimento pontual, acho que vale um texto pré-definido?

**Comment by volooptaz** [comment]
Boa preocupação,  Zei. Vou abrir uma issue para discutirmos essas questões, porque essas threads "Materiais" gerais já foram compiladas todas lá no OpenBlouco e aí podemos direcionar melhor as issues, tá?
