### ISSUE TITLE
Criar templates das Páginas das Funções

### ISSUE THREAD

**Issue by volooptaz** [blouco/openblouco#25]
Desenhar, com input de #23 e coordenação com  @volooptaz na #24, as páginas HTML que gerarão as páginas de cada função à maneira como está sendo desenvolvida a da Incauta / Rua.

Para simplificar e não ser necessário aprender os templates do Flask, @zeivic você pode criar várias páginas que variem somente com relação a algum `<div>` ou outro container interno, que é onde entram as especificidades de cada página.

Que acha?

**Comment by zeivic** [comment]
Vou montar então uma página esqueleto e você vai replicar?

**Comment by volooptaz** [comment]
App sendo desenvolvido dentro do próprio repo orignal do HashFolia:

https://github.com/blouco/hash-folia

Instância online:

https://hash.bloucos.art/hash/TesteDoHashFolia
