### ISSUE TITLE
Escolha de plataforma de Webchat - Papo / Cordão

### ISSUE THREAD

**Issue by volooptaz** [blouco/openblouco#3]
IRC / Webchat Freenode

https://webchat.freenode.net/

- Usa o KiwiIRC que é bem amigável e pode ser embedado na página principal
- IRC é bem leve e pode ser acessado de outras ferramentas 
- Estrutura de canais e poderes (voice, op) simples e útil para  as dinâmica do Papo e do - Cordão, além depodper abrigar salas auxiliares para os outros ambientes
- Contato com a comunidade de software livre
- Fator nostalgia
- Fácil de construir bots simples para diversão ou funções úteis dentro da sala.

**Comment by zeivic** [comment]
existe uma questão sobre a exibição dele em mobile, fiz um alternativa em [#ajuste no Kiwiirc](https://github.com/blouco/openblouco/commit/8e7b4d065157d2a97b23c96a34845ce7dba92c5a) vê se faz sentido. Pensei que o chat poderia ficar do lado da transmissão o que acham?

**Comment by volooptaz** [comment]
Ótimo @zeivic . Eu vou criar um repositório separado do openblouco para o nosso gerador, e levar o que você já fez pra lá, conectado a ideia de salas para cada função que elaborei em #1, mas enquanto isso pode continuar trabalhando nele aqui mesmo.

Olha, o próprio KiwiIRC pode ser 

A gente já estando com nosso próprio servidor, podemos pensar também mais pra frente em hospedar/servir diretamente o código do KiwiIRC, e aí podemos customizar o CSS dele (como estamos embedando num iframe não funciona) 

https://kiwiirc.com/docs/theming

**Comment by volooptaz** [comment]
Também há configurações extras que podem ser usadas mesmo usando o KiwiIRC hospedado externamente: https://github.com/kiwiirc/kiwiirc/wiki/Configuration

A mais interessante parece ser a de configurar um nick. Podemos colocar o nick como "**Incauta_{num}**", em vez do "kiwi" que vem pro padrão e que em geral já está registrado (E causa uma estranheza na pessoa)

**Comment by volooptaz** [comment]
Bem, escolhemos o KiwiIRC webchat mesmo. Já temos uma implementação dele funcionando no código do https://github.com/blouco/hash-folia. Fechando a issue
